show databases;
show tables;
create database COMPUTER_ENGINEERING;

drop table COMPUTER_ENGINEERING;
create database COURSES;
create database STUDENTS;

use TELECOMMUNICATION_ENGINEERING;
use COMPUTER_ENGINEERING;
drop table FIRST_YEAR;
create table FIRST_YEAR 
(ID int, STUDENT_NAME varchar(100),REG_NO varchar(100),COURSES varchar(100),IMAGE blob);
drop table SECOND_YEAR;
create table SECOND_YEAR 
(ID int, STUDENT_NAME varchar(100),REG_NO varchar(100),COURSES varchar(100),IMAGE blob);
drop table THIRD_YEAR;
create table THIRD_YEAR 
(ID int, STUDENT_NAME varchar(100),REG_NO varchar(100),COURSES varchar(100),IMAGE blob);
drop table FOURTH_YEAR;
create table FOURTH_YEAR 
(ID int, STUDENT_NAME varchar(100),REG_NO varchar(100),COURSES varchar(100),IMAGE blob);


select * from FIRST_YEAR;
select * from SECOND_YEAR;
select * from THIRD_YEAR;
select * from FOURTH_YEAR;
select * from COMPUTER_ENGINEERING;

use COURSES;
create table FUCULTIES 
(ID int, TELECOMMUNICATION_ENGINEERING varchar(100),COMPUTER_ENGINEERING varchar(100));
insert into FUCULTIES 
values (1,'FIRST_YEAR','FIRST_YEAR'),
		(2,'SECOND_YEAR','SECOND_YEAR'),
        (3,'THIRD_YEAR','THIRD_YEAR'),
        (4,'FOURTH_YEAR','FOURTH_YEAR');

create table TE_COURSES
(ID int, FIRST_YEAR  varchar(100),SECOND_YEAR  varchar(100),THIRD_YEAR  varchar(100),FOURTH_YEAR  varchar(100));
create table CEIT_COURSES
(ID int, FIRST_YEAR  varchar(100),SECOND_YEAR  varchar(100),THIRD_YEAR  varchar(100),FOURTH_YEAR  varchar(100));
insert into TE_COURSES values
    ('1','ES173 : INTRODUCTION TO ELECTRICAL CIRCUITS','ES110 : ANALOGUE ELECTRONICS I','TE231 : FUNDAMENTALS OF SIGNALS AND SYSTEMS','TE411 : MICROWAVE COMMUNICATION'),
('2','CL111 : COMMUNICATION SKILLS FOR ENGINEERS','ES171 : COMPUTER AIDED DRAFTING AND DESIGN (CADD)','TE380 : DIGITAL SIGNAL PROCESSING (DSP)','TE415 : OPTICAL COMMUNICATION'),
('3','CS174 : PROGRAMMING IN C','CS175 : PROGRAMMING IN JAVA','TE331 : PRINCIPLES OF ANALOGUE TELECOMMUNICATIONS','TE443 : DIGITAL BROADCASTING TECHNOLOGIES'),
('4','DS112 : DEVELOPMENT PERSPECTIVES I','DS113 : DEVELOPMENT PERSPECTIVES II','TE337 : TELE-TRAFFIC ENGINEERING','TE444 : TELECOMMUNICATIONS POLICY AND REGULATION'),
('5','ME101 : ENGINEERING DRAWING','ES120 : DIGITAL ELECTRONICS I','CS348 : NETWORK SWITCHING AND ROUTING','IE441 : HUMAN RESOURCE MANAGEMENT FOR ENGINEERS'),
('6','MT161 : MATRICES AND BASIC CALCULUS FOR NON-MAJORS','IS171 : INTRODUCTION TO COMPUTER NETWORKS','IE354 : ENGINEERING PROJECT MANAGEMENT','TE447 : WIRELESS TECHNOLOGIES');

insert into CEIT_COURSES values
('1','ES173 : INTRODUCTION TO ELECTRICAL CIRCUITS','CS243 : COMPUTER NETWORK DESIGN AND ADMINISTRATION','CS348 : NETWORK SWITCHING AND ROUTING','CS323 : CONTROL SYSTEMS ENGINEERING'),
('2','CL111 : COMMUNICATION SKILLS FOR ENGINEERS','CS234 : OBJECT ORIENTED PROGRAMMING IN JAVA','CS354 : MICROCOMPUTER SYSTEMS II','ES324 : SYSTEM DESIGN AND IMPLEMENTATION'),
('3','CS174 : PROGRAMMING IN C','ES211 : ANALOGUE ELECTRONICS I','CS356 : EMBEDDED SYSTEMS','TE334 : INFORMATION THEORY'),
('4','DS112 : DEVELOPMENT PERSPECTIVES I','ES221 : DIGITAL ELECTRONICS II','IS336 : PRINCIPLE OF SYSTEMS SECURITY','TE415 : OPTICAL COMMUNICATION'),
('5','ME101 : ENGINEERING DRAWING','ES213 : ELECTRONICS INSTRUMENTATION I','IS365 : ARTIFICIAL INTELLIGENCE','TE339 : TELECOMMUNICATION SWITCHING AND TRANSMISSION'),
('6','MT161 : MATRICES AND BASIC CALCULUS FOR NON-MAJORS','IS274 : OBJECT ORIENTED ANALYSIS AND DESIGN','TE 332 : PRINCIPLE OF DIGITAL TELECOMMUNICATIONS','TE411 : MICROWAVE COMMUNICATION');

select * from TELECOMMUNICATION_ENGINEERING;
select * from COMPUTER_ENGINEERING;
select * from FUCULTIES;


    
